Update SaveSystem.cs
Library\PackageCache\com.lonecraftgames.toolkit@33ccffb6fe41\Runtime\Save\Scripts\SaveSystem.cs(124,66): error CS1503: Argument 2: cannot convert from 'bool' to 'string'